syntax = "proto3";

package connPlayer;

option go_package = "github.com/goggle-source/connPlayerLotProto/gen/go/connPlayer;connPlayer";

service ConnPlayer {
    rpc MaltingAllPlayers(MaltingAllPlayersRequest) returns (MaltingAllPlayersResponse);
    rpc SendMessageUser(SendMessageUserRequest) returns (SendMessageUserResponse);
}

message MessageUser {
    int32 place = 1;
    string message = 2;
}

message MaltingAllPlayersRequest {
    string auction_id = 1;
    string message = 2;
}

message MaltingAllPlayersResponse {}

message SendMessageUserRequest {
    string auction_id = 1;
    MessageUser message = 2;
}

message SendMessageUserResponse {}